files:
    - source: /packages/bot/locales/en-US/*.json
      translation: /packages/bot/locales/%{use_locale}%/%original_file_name%
      languages_mapping:
          use_locale:
              bg: 'bg'
              zh-CN: 'zh-CN'
              zh-TW: 'zh-TW'
              hr: 'hr'
              cs: 'cs'
              da: 'da'
              nl: 'nl'
              en-GB: 'en-GB'
              en-US: 'en-US'
              fi: 'fi'
              fr: 'fr'
              de: 'de'
              el: 'el'
              hi: 'hi'
              hu: 'hu'
              id: 'id'
              it: 'it'
              ja: 'ja'
              ko: 'ko'
              lt: 'lt'
              no: 'no'
              pl: 'pl'
              pt-BR: 'pt-BR'
              ro: 'ro'
              ru: 'ru'
              es-ES: 'es-ES'
              sv-SE: 'sv-SE'
              th: 'th'
              tr: 'tr'
              uk: 'uk'
              vi: 'vi'
