'files':
    [
        {
            'source': '/packages/bot/locales/en-US/*.json',
            'translation': '/packages/bot/locales/%locale%/%original_file_name%',
            'languages_mapping':
                {
                    'locale':
                        {
                            'bg-BG': 'bg',
                            'cs-CZ': 'cs',
                            'da-DK': 'da',
                            'de-DE': 'de',
                            'el-GR': 'el',
                            'fi-FI': 'fi',
                            'fr-FR': 'fr',
                            'hi-IN': 'hi',
                            'hr-HR': 'hr',
                            'hu-HU': 'hu',
                            'id-ID': 'id',
                            'it-IT': 'it',
                            'ja-JP': 'ja',
                            'ko-KR': 'ko',
                            'lt-LT': 'lt',
                            'nl-NL': 'nl',
                            'no-NO': 'no',
                            'pl-PL': 'pl',
                            'ro-RO': 'ro',
                            'ru-RU': 'ru',
                            'th-TH': 'th',
                            'uk-UA': 'uk',
                            'vi-VI': 'vi',
                        },
                },
        },
    ]
