'project_id': 'CROWDIN_PROJECT_ID'
'api_token': 'CROWDIN_PERSONAL_TOKEN'
'base_path': '/packages/bot/locales/'
'base_url': 'https://api.crowdin.com'
'preserve_hierarchy': true
'files':
    [
        {
            'source': '/packages/bot/locales/en-US/*.json',
            'translation': '/packages/bot/locales/%locale%/%original_file_name%',
        },
    ]
