files:
    - source: /packages/bot/locales/en-US/*.json
      translation: /packages/bot/locales/%code_type%/%original_file_name%
      languages_mapping:
          code_type:
              bg: 'two_letters_code'
              zh-CN: 'locale'
              zh-TW: 'locale'
              hr: 'two_letters_code'
              cs: 'two_letters_code'
              da: 'two_letters_code'
              nl: 'two_letters_code'
              en-GB: 'locale'
              en-US: 'locale'
              fi: 'two_letters_code'
              fr: 'two_letters_code'
              de: 'two_letters_code'
              el: 'two_letters_code'
              hi: 'two_letters_code'
              hu: 'two_letters_code'
              id: 'two_letters_code'
              it: 'two_letters_code'
              ja: 'two_letters_code'
              ko: 'two_letters_code'
              lt: 'two_letters_code'
              no: 'two_letters_code'
              pl: 'two_letters_code'
              pt-BR: 'locale'
              ro: 'two_letters_code'
              ru: 'two_letters_code'
              es-ES: 'locale'
              sv-SE: 'locale'
              th: 'two_letters_code'
              tr: 'two_letters_code'
              uk: 'two_letters_code'
              vi: 'two_letters_code'
